### ISSUE TITLE
Server cannot load AutoClaimChallenges

### ISSUE THREAD

**Issue by istrasci** [unv-annihilator/7D2D_Mods#12]
My hosted server cannot load the **AutoClaimChallenges** mod.  All I'm supposed to do is upload the mod .zip file and restart the server.  This is the server output I see.

> 2024-08-22T05:45:07 1.156 INF [MODS] **Start loading from: '/home/sdtd58240/sdtd/bin/7DaysToDieServer_Data/../Mods'**
> 2024-08-22T05:45:07 1.164 INF [MODS]   **Trying to load from folder: 'AutoClaimChallenges'**
> 2024-08-22T05:45:07 1.171 INF [MODS]     **Loaded Mod: AutoClaimChallenges (0.1.0.0)**
> 2024-08-22T05:45:07 1.172 INF [MODS] **Initializing mod code**
> 2024-08-22T05:45:07 1.173 INF [MODS]   **Initializing mod AutoClaimChallenges**
> 2024-08-22T05:45:07 1.174 INF [MODS]     **Found ModAPI in AutoClaimChallenges.dll, creating instance**
> 2024-08-22T05:45:07 1.176 ERR [MODS]     **Failed initializing ModAPI instance on mod 'AutoClaimChallenges' from DLL 'AutoClaimChallenges.dll'**
> 2024-08-22T05:45:07 1.187 INF [MODS] **Loading done**

Any ideas?

**Comment by unv-annihilator** [comment]
That mod is client side only so will not work on servers. But you can install it on your client and use it while on a server, just has to be installed on the client side.
